[package]
name = "sqlite2kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-rdb2kv = { path = "../../" }
rusqlite = "0.28.0"
